// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteApp.Data;

#nullable disable

namespace RestauranteApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RestauranteApp.Domain.Entities.CategoriaMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("CategoriasMenu");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoImpresion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HoraEnvio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosImpresion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UltimoErrorImpresion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoIntentoImpresion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoImpresionTicket")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HoraCobro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Propina")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.ItemMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alergenos")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoriaMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaMenuId");

                    b.ToTable("ItemsMenu");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.ItemOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModificadorIdsCsv")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreItem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("ItemMenuId");

                    b.HasIndex("OrdenId");

                    b.ToTable("ItemsOrden");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrdenActivaId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdenActivaId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Mesero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMesero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("NumeroMesero")
                        .IsUnique();

                    b.ToTable("Meseros");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.ModificadorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioExtra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ItemMenuId");

                    b.ToTable("ModificadoresItem");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Folio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistorialTraspasos")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraCierre")
                        .HasColumnType("TEXT");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeseroId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.HasIndex("MesaId");

                    b.HasIndex("MeseroId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuentaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Metodo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.RegistroImpresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreImpresora")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RegistrosImpresion");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("decimal(5,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Comanda", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.Orden", "Orden")
                        .WithMany("Comandas")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.Orden", "Orden")
                        .WithOne("Cuenta")
                        .HasForeignKey("RestauranteApp.Domain.Entities.Cuenta", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.ItemMenu", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.CategoriaMenu", "CategoriaMenu")
                        .WithMany("Items")
                        .HasForeignKey("CategoriaMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaMenu");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.ItemOrden", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.Comanda", "Comanda")
                        .WithMany("Items")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestauranteApp.Domain.Entities.ItemMenu", "ItemMenu")
                        .WithMany()
                        .HasForeignKey("ItemMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Domain.Entities.Orden", "Orden")
                        .WithMany("Items")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("ItemMenu");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Mesa", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.Orden", "OrdenActiva")
                        .WithMany()
                        .HasForeignKey("OrdenActivaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestauranteApp.Domain.Entities.Zona", "Zona")
                        .WithMany("Mesas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenActiva");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.ModificadorItem", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.ItemMenu", "ItemMenu")
                        .WithMany("Modificadores")
                        .HasForeignKey("ItemMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMenu");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Orden", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Domain.Entities.Mesero", "Mesero")
                        .WithMany()
                        .HasForeignKey("MeseroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Mesero");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Pago", b =>
                {
                    b.HasOne("RestauranteApp.Domain.Entities.Cuenta", "Cuenta")
                        .WithMany("Pagos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.CategoriaMenu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Comanda", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.ItemMenu", b =>
                {
                    b.Navigation("Modificadores");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Orden", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("Cuenta");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestauranteApp.Domain.Entities.Zona", b =>
                {
                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
